### ISSUE TITLE
not kicking in when the colorscheme set by autocmd

### ISSUE THREAD

**Issue by jmlucjav** [folke/lsp-colors.nvim#2]
hi, 

first able, this is wonderful, will allow me to use ariake colorscheme...but I have an issue.

I change colorschemes depending on the file I'm editing:

```
augroup colors
    au!
    autocmd BufEnter * colorscheme space-nvim | set background=light
    autocmd BufEnter *.py colorscheme ariake | set background=light
augroup END
```

When I open a python file, the diagnostics are not shown properly. If I just do this (being already in ariake):

:colorscheme ariake

then suddenly it works. Chanign to something else and coming back to ariake also works. I verified if I just set airake in my init.vim and remove the per filetype stuff the plugin works normally.

I'm in master as of today.
thanks!

**Comment by folke** [comment]
I was able to transfer the issue. Didnt know that was possible :)

**Comment by jmlucjav** [comment]
> @jmlucjav no worries, you can keep it here, but i was a bit confused 😂
> 
> Did you try adding the `nested` option? That should fix it.

I didn't understand what is nested, but I blindly added it, and it works, wonderful. many thanks

**Comment by folke** [comment]
Haha, perfect.

So what nested does, is allow any other events triggered by your autocmd to fire.

The `colorscheme` command normally triggers the `ColorScheme` event, but if you run it from within an autocmd, it won't fire by default.

Adding the `nested` option allows commands in your `autocmd` to fire events as well.

Hope this makes more sense now ;)

**Comment by hrqmonteiro** [comment]
> To make that work, you'll need to add `nested` before the `colorscheme` 
command in your config. Otherwise the `ColorScheme` event won't be triggered, meaning `lsp-colors` can't fix your colorscheme.

Hi, could you explain that more detailed? I don't quite understand how to do it.

I am having the same problem as OP, i call `vim.cmd 'set colorscheme nord'` in my init.lua and it was all fine. But the plugin doesn't kick in unless i set in manually again.

How exactly do i do this nested config?

**Comment by folke** [comment]
@hrqmonteiro you should not include the `set` in your CMD. That syntax is not correct

**Comment by folke** [comment]
Ops problem was because he changed the colorscheme in an autocmd without nested. If you're not doing that, then this is something different.

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro you should not include the `set` in your CMD. That syntax is not correct

My mistake, it's actually not that, just `vim.cmd 'colorscheme nord'`

And even like this, is not kicking in.

When i open a file:

![2021-05-20_08-00](https://user-images.githubusercontent.com/17055027/118967731-7280f980-b941-11eb-81f3-85667c23c96a.png)

After i manually re-set the color scheme in the cmd:

![2021-05-20_08-00_1](https://user-images.githubusercontent.com/17055027/118967790-8167ac00-b941-11eb-80bb-2a56d0947149.png)

**Comment by folke** [comment]
@hrqmonteiro that's weird. How are you loading lsp-colors? and when do you do colorscheme? Package manager?

**Comment by folke** [comment]
After opening the file, when it is wrong, what does `:verbose hi LspDiagnosticsUnderlineError` give?
