### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Chaitanyabsprip** [folke/lsp-colors.nvim#3]
![Screenshot:2021-05-15](https://user-images.githubusercontent.com/55058351/118355304-e5c6ec00-b58c-11eb-84a0-96eba351fc48.png)

I dont think this is desired outcome
```lua 
use {
    "folke/lsp-colors.nvim",
    config = function()
      require("lsp-colors").setup({
        Error = "#db4b4b",
        Warning = "#e0af68",
        Information = "#0db9d7",
        Hint = "#10B981"
      })
    end
  }
```

**Comment by folke** [comment]
It seems that the terminal you are using does not support undercurls.

It works in Kitty

**Comment by Chaitanyabsprip** [comment]
I am using kitty

**Comment by folke** [comment]
Inside tmux?

**Comment by Chaitanyabsprip** [comment]
nope, vanilla kitty, nothing else

**Comment by folke** [comment]
What does `:verbose hi LspDiagnosticsUnderlineError` give?

Also, it seems you're using my TokyoNight theme? That already includes all the proper highlight groups for undercurls, so you don't need `lsp-colors` for this color scheme.

**Comment by Chaitanyabsprip** [comment]
```LspDiagnosticsUnderlineError xxx gui=undercurl guisp=#db4b4b                                                                   
        Last set from anonymous :source```
even if tokyonight has it, its still not working for some reason

**Comment by folke** [comment]
Yep, it's definitely an issue with your terminal or possibly the Neovim build you use.

Maybe try updating both?

**Comment by folke** [comment]
What does `printf '\e[4:3mUnderlined\n'` do in the terninal?

Is `$TERM` set to `xterm-kitty`?

**Comment by Chaitanyabsprip** [comment]
I am using Kitty v0.20.2-1 which is the latest release and I am using NVIM v0.5.0-dev+1321-gc57a85d53 which is the latest pre-release. 



> What does `printf '\e[4:3mUnderlined\n'` do in the terninal?
![Screenshot:2021-05-15_001](https://user-images.githubusercontent.com/55058351/118357280-e5cbe980-b596-11eb-8989-737a190ef098.png)

> Is `$TERM` set to `xterm-kitty`?
the issue was this env-variable. it was not xterm-kitty, now that works fine. 

Q: I can uninstall this extension right, as I am using tokyonight?

**Comment by folke** [comment]
Yep, this extension only adds the missing highlight groups, for colorschemes that don't define them. Glad you got this working!

**Comment by Chaitanyabsprip** [comment]
Thank you for you help
