### ISSUE TITLE
underlines' color not matching the diagnostic color

### ISSUE THREAD

**Issue by LuisxSullivaN** [folke/lsp-colors.nvim#6]
Sorry if it's not related to this plugin but I was some way hoping installing this could get it to work, the issue I have is that I think the underline color should be red (in this case) as you show in the screenshots despite I don't have undercurls but correct me if I'm wrong. 
![image](https://user-images.githubusercontent.com/29529436/127697519-eed2b44a-200c-4016-8ef8-329f23ac9aa3.png)

**Comment by folke** [comment]
You need a terminal that supports different colors for underlines as well. You should test in Kitty instead.

**Comment by LuisxSullivaN** [comment]
Actually I realized I needed to change guisp=<color> config in my colorscheme for the corresponding highlight group. Of course a terminal supporting that feature is also required.

**Comment by folke** [comment]
@LuisxSullivaN ah yes, of course. That;s indeed what you need to specify a different color. Glad you got that working :)
