### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SleepyCatOnTheBed** [folke/lsp-colors.nvim#7]
I am have installed the plugins, config in lua files then source in the init.vim. However, it still not working, are there any solution ?
Neovim: 0.5
Terminal: Kitty

![image](https://user-images.githubusercontent.com/71932200/129446762-3011d4ed-7e82-40a6-b7ab-074676314cee.png)

**Comment by folke** [comment]
Which ColorScheme are you using?

**Comment by SleepyCatOnTheBed** [comment]
For some reasons, the gruvbox colorscheme doesn't work perfectly for me, i installed the gruvbox-material instead. That is why i use the lua default code you provided

**Comment by SleepyCatOnTheBed** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/71932200/129450512-5722467d-075c-4fb9-b1cb-fe0195d5670f.png)

**Comment by neezer** [comment]
Also don't have this working with [arcticstudio/nord-vim](https://github.com/arcticicestudio/nord-vim). Pretty sure I followed your README to the letter. Let me know what kind of diagnostic information would be useful to have.

**Comment by SleepyCatOnTheBed** [comment]
I have tried to reinstall my colorscheme, and everything work perfectly now. Thank for helping me. I will close the issue now.

**Comment by neezer** [comment]
Oh, nm. I'm an idiot. The warnings should be blue; I thought I was looking at an error. ☕ ☕ ☕
